### ISSUE TITLE
Can this be used with real Sparkassen accounts already?

### ISSUE THREAD

**Issue by bentalexanderhaase** [sparkassen-hub/ahoi-nodejs-client#2]
If you'd like to fetch a real (existing live) accounts balance, can this already be done with AHOI? All documentation is pretty unclear about this and does not clearly deny use in production environments / the use with real banking accounts.

**Comment by ufafath** [comment]
Hey @ET-Ben,
contact us via ahoi-api@starfinanz.de, please.
Kind regards
You AHOI-Team

**Comment by MadddinTribleD** [comment]
@ET-Bent  would you mind adding me as CC?
My mail is github@martin.gafert.org

**Comment by bentalexanderhaase** [comment]
@ufafath I sent an e-mail on **12.06.2019** to `ahoi-api@starfinanz.de`. 
This issue can be closed.

**Comment by MadddinTribleD** [comment]
Transcript of the mail (I guess this could be usefull for others)  

> Hallo Bent,
> 
> vielen Dank für deine Anfrage.  
> Auf dem Sandbox System können wir aktuell nur Demo-Daten zulassen.  
> Hintergrund dafür ist, dass wir aktuell noch nicht im Besitz  einer ZAG-Erlaubnis sind (Zahlungsdiensteaufsichtsgesetz) und wir können aktuell auch noch nicht abschätzen wann wir diese erhalten werden.  
> D.h. wir befinden uns i.d.R. im PSD2-Kontext (Payment Service Directrive 2), auf unserem produktiven System können wir aktuell somit nur Szenarien bedienen, die sich nicht im PSD2-Kontext befinden.  
> Auf dem produktiven System sind aktuell alle Banken und Sparkassen erreichbar, die FinTS mit PIN und TAN unterstützen.  
>   
> Wir hoffen, dies beantwortet deine Fragen. Solltest du dennoch Fragen haben melde dich gerne oder schau in unsere FAQs (https://banking-sandbox.starfinanz.de/ahoi/docs/cookbook/index.html#faq).  
>   
> Viele Grüße  
> Dein AHOI-Team  
>   
> Von: Bent Haase <***@***.***>   
> Gesendet: Mittwoch, 12. Juni 2019 12:52  
> An: ahoi-api <ahoi-api@starfinanz.de>  
> Cc: ***@***.***  
> Betreff: regarding issue #2 'sparkassen-hub/ahoi-nodejs-client'  
>   
> > Dear AHOI/Starfinanz team,  
> > I am contacting you regarding my GitHub issue #2 as requested by ufafath (Uwe Fath). I would like to know if I can already use the AHOI API to access my personal bank account and gather data like my current balance, accounts and transactions (without any commercial interests).  
> > I put Martin Gafert (aka. MadddinTribleD) into CC on purpose, we are working together.  
> > As I am a native German speaker you may also reply in German.  
> > Best regards  
> > Bent Alexander Haase

**Comment by mspoerer** [comment]
Any news on this topic? When can we expect to have access to real bank accounts? Is it a matter of days, weeks, month...? Do you guys already have a pricing model or will it be for free? I some how could not find any news to those topics. Thx in advanced.
